### ISSUE TITLE
#messageBox: overweight and underweight

### ISSUE THREAD

**Issue by aikochanni** [Gwenillia/Better-Equideow#66]
Hi!
I used your work while tooling my horses and came up with something that can be implemented.
Because the automatic selection of feed and oats did not take into account message boxes about overweight and underweight horses.
I made a slight remaster for personal use (Polish version of the game).
Could you see if you would like to implement it in your own way?

```
this.messageBox = document.getElementById("messageBoxInline").textContent; // in the constructor()

switch (true) {
      case this.messageBox.includes("Nie karm"): // howrse.com "anything to eat today"
        break;
      case this.messageBox.includes("ilość paszy: 20"): // howrse.com "20 fodder today to bring"
        this.haySelectors[20].click();
        break;
      case this.messageBox.includes("ilość paszy: 16"): //howrse.com "16 fodder today to bring"
        this.haySelectors[16].click();
        break;
      default:
        if (fourrageNode) {
          const fourrageIndex = this.getFoodIndex(fourrageNode);
          this.haySelectors[fourrageIndex].click();
        }

        if (avoineNode) {
          const avoineIndex = this.getFoodIndex(avoineNode);
          this.oatsSelectors[avoineIndex].click();
        }
        break;
    }
```
    Have a nice day / night! ^^

**Comment by Gwenillia** [comment]
Hi, thank you. I will check it later but thanks for the suggestion, I didn't think about these warning messages ahah. I will solve this problem.

Also, I can implement the polish language maybe

**Comment by Gwenillia** [comment]
Created #67 and #68
