### ISSUE TITLE
add polish language support

### ISSUE THREAD

**Issue by Gwenillia** [Gwenillia/Better-Equideow#68]
maybe @aikochanni could help 🥺 
Or any PL speaker. 

TODO: 
- [ ] add pl translations corresponding to the game

**Comment by aikochanni** [comment]
Hi! I apologize to you for my long absence. If still relevant, sure, I don't see a problem! But you have to tell me what and where exactly ^^

**Comment by Gwenillia** [comment]
Mh If you're not familiar with github it may be a bit complex but here is the [documentation](https://github.com/Gwenillia/Better-Equideow/blob/main/CONTRIBUTING.md#pull-requests) 

Otherwise you can just provide the strings here since it's not a lot of sentences ahah

**Comment by Gwenillia** [comment]
I’m gonna close this issue. Feel free to reopen one when needed
