### ISSUE TITLE
Feat: Add gender info in the moreInfo section

### ISSUE THREAD

**Issue by AndreaMendez09** [Gwenillia/Better-Equideow#80]
Hi! 
Im working on this feature but im not a JS developer, im a Backend in Java so feel free to correct me if u need it.

At the moment I have this done:
![imagen](https://github.com/Gwenillia/Better-Equideow/assets/47080611/c5523b55-4efb-4ec5-9999-23e7f884f66b)

The problem im facing is with the integration with the other languages:
![imagen](https://github.com/Gwenillia/Better-Equideow/assets/47080611/1100ed4b-ef5a-4b9b-878b-5d6d7e33bea9)
They dont have an ID for the gender part, so I have to do it like this:
`this.regexpSexHtml = /<td class="first"><strong>Sexo:<\/strong>\s*(\w+)<\/td>/`

How can I make this work for the rest of the languages?

Another thing, when you go to the buy horses part, when added this feature you see this:
![imagen](https://github.com/Gwenillia/Better-Equideow/assets/47080611/91f8ad63-2368-4ee3-a552-f0cc9feea33f)
I think im doing somethin wrong or in a wrong file.

And the last thing I want to ask is, I believe this can be done better:

              const sexHTML = data.match(this.regexpSexHtml);
              const img = document.createElement("img")
              if (sexHTML[1] === `${translation.get(this.lang, 'sex', 'female')}`) {
                img.src = chrome.runtime.getURL("images/female.png")
              } else if (sexHTML[1] === `${translation.get(this.lang, 'sex', 'male')}`) {
                img.src = chrome.runtime.getURL("images/male.png")
              } else {
                img.src = chrome.runtime.getURL("images/gelding.png")
              }
I was trying to do something like this:

`const imageUrl = chrome.runtime.getURL(images/${sexValue}.png);`

The concept its to delete de ifs statements, and simplify the code, but with the translation feature i dont know how to do it.

Thanks for your help! I will update in the comments if I find a solution for any of this problems.

The branch im working in --> [https://github.com/AndreaMendez09/Better-Equideow/tree/more-info-horse-gender]( https://github.com/AndreaMendez09/Better-Equideow/tree/more-info-horse-gender)

**Comment by Gwenillia** [comment]
Sure, can you please open a PR when it’s fixed, or if you want me to fix it just tag me :) 

For the first thing: I think you can use the xPath of the element or something like that 🤔 

For the bug on buy horse part, you can display the icon only when `this.elevageLocation` is true 
https://github.com/Gwenillia/Better-Equideow/blob/0c99878ac38e1d971961251656c6fc5041a0dbd1/moreInfos.js#L28
This line should be the same on all howrse websites since the url seems to always be in french.

**Comment by AndreaMendez09** [comment]
Thanks! I manage with your help to make it work, I will do a PR, the only thing thats incomplete its the translation file for PL and NO.
